eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8763
spring:
  application:
    name: eurekaclient
  #服务链路追踪
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
management:
  security:
    #关闭安全验证，否则访问refresh端点时会提示权限不足
    enabled: false
# spring:
#     zipkin:
#         base-url: http://localhost:9411
#     sleuth:
#         sampler:
#             percentage: 1.0
