server:
  port: 8765
spring:
  application:
    name: feign
eureka:
  client: 
    service-id:
      defaultZone: http://localhost:8888/eureka/
#熔断器
feign:
  hystrix:
    enabled: true
    
# management:
#   endpoints:
#     web:
#       exposure:
#         include: "*"
