eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
server:
  port: 8764
spring:
  application:
    name: gateway
zuul:
  routes:
    api:
      path: /api/**
      service-id: client
