server: 
  port: 8764
eureka: 
 client:
   service-url:
     defaultZone: http://localhost:8888/eureka/
spring: 
  application: 
    name: gateway
zuul: 
  routes: 
    api: 
      path: /api/**
      service-id: client
